spring:
  application:
    name: holidaymanager

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    open-in-view: false

  sql:
    init:
      mode: always

springdoc:
  paths-to-match: /**
  cache:
    disabled: true

server:
  error:
    include-stacktrace: never
    whitelabel:
      enabled: false

logging:
  level:
    org.springframework: ERROR
